### PR TITLE
increment build number to force rebuild with hotfix

### PR DESCRIPTION
**Pull request by gonuke**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Updated release with hotfix for version number in CMake

### CODE REVIEW

**Comment by gonuke** [comment]
@conda-forge-admin, please rerender

**Review by shimwell — APPROVED** [review]

**Comment by shimwell** [comment]
Looks good, I did the same on PR #9 so I shall close #9 now

**Comment by pshriwise** [comment]
Do we know why the hdf5 lines were removed?

**Comment by gonuke** [comment]
I re-rendered, so maybe they weren't needed in the first place?

**Comment by gonuke** [comment]
I usually don't review the autogenerated code - only the recipe files

**Review by pshriwise — APPROVED** [review]

**Comment by shimwell** [comment]
Yep, I think we just review the recipe/meta.yaml and recipe/build.sh files

**Pull request merged**
